export interface NewsSource {
  name: string;
  domain: string;
  type: 'National' | 'Regional' | 'Local' | 'Community' | 'Official' | 'Blog';
  geography?: string;
}

export const SOUTH_AFRICAN_NEWS_SOURCES: NewsSource[] = [
  // National News
  { name: 'News24', domain: 'news24.com', type: 'National' },
  { name: 'TimesLive', domain: 'timeslive.co.za', type: 'National' },
  { name: 'IOL (Independent Online)', domain: 'iol.co.za', type: 'National' },
  { name: 'Daily Maverick', domain: 'dailymaverick.co.za', type: 'National' },
  { name: 'The Citizen', domain: 'citizen.co.za', type: 'National' },
  { name: 'Sowetan Live', domain: 'sowetanlive.co.za', type: 'National' },
  { name: 'Mail & Guardian', domain: 'mg.co.za', type: 'National' },
  { name: 'SABC News', domain: 'sabcnews.com', type: 'National' },
  { name: 'eNCA', domain: 'enca.com', type: 'National' },
  { name: 'Eyewitness News (EWN)', domain: 'ewn.co.za', type: 'National' },
  { name: 'BusinessLive', domain: 'businesslive.co.za', type: 'National' },
  { name: 'Fin24', domain: 'fin24.com', type: 'National' },
  { name: 'Moneyweb', domain: 'moneyweb.co.za', type: 'National' },
  { name: 'Politicsweb', domain: 'politicsweb.co.za', type: 'National' },
  { name: 'GroundUp', domain: 'groundup.org.za', type: 'National' },
  { name: 'The South African', domain: 'thesouthafrican.com', type: 'National' },
  { name: 'Daily Sun', domain: 'snl24.com/dailysun', type: 'National' },
  { name: 'Vrye Weekblad', domain: 'vryeweekblad.com', type: 'National' },
  { name: 'Maroela Media', domain: 'maroelamedia.co.za', type: 'National' },
  { name: 'Netwerk24', domain: 'netwerk24.com', type: 'National' },

  // Eastern Cape Regional (Major)
  { name: 'Daily Dispatch (DispatchLIVE)', domain: 'dispatchlive.co.za/news', type: 'Regional', geography: 'Eastern Cape' },
  { name: 'The Herald (HeraldLIVE)', domain: 'heraldlive.co.za/news', type: 'Regional', geography: 'Eastern Cape' },
  { name: 'Grocott\'s Mail', domain: 'grocotts.co.za', type: 'Regional', geography: 'Makhanda' },
  { name: 'Go! & Express', domain: 'snl24.com/go-express/news', type: 'Regional', geography: 'East London' },
  { name: 'Algoa FM News', domain: 'algoafm.co.za/news', type: 'Regional', geography: 'Eastern Cape' },
  { name: 'TruFM News', domain: 'sabcnews.com/sabcnews/category/south-africa/eastern-cape/', type: 'Regional', geography: 'Eastern Cape' },
  { name: 'Umhlobo Wenene FM', domain: 'sabcnews.com/sabcnews/category/south-africa/eastern-cape/', type: 'Regional', geography: 'Eastern Cape' },

  // Eastern Cape Local & Community (Comprehensive)
  { name: 'Mthatha Express', domain: 'snl24.com/mthatha-express/news', type: 'Local', geography: 'Mthatha' },
  { name: 'PE Express', domain: 'pe-express.co.za', type: 'Local', geography: 'Gqeberha' },
  { name: 'Kouga Express', domain: 'kougaexpress.co.za', type: 'Local', geography: 'Kouga' },
  { name: 'UD News', domain: 'snl24.com/ud-news/news', type: 'Local', geography: 'Uitenhage/Despatch' },
  { name: 'The Representative (The Rep)', domain: 'therep.co.za', type: 'Local', geography: 'Komani' },
  { name: 'Talk of the Town', domain: 'talkofthetown.co.za/category/news/', type: 'Local', geography: 'Port Alfred' },
  { name: 'Barkly East Reporter', domain: 'snl24.com/barkly-east-reporter/news', type: 'Local', geography: 'Barkly East' },
  { name: 'Winterberg News', domain: 'snl24.com/winterberg-news/news', type: 'Local', geography: 'Adelaide/Bedford' },
  { name: 'St Francis Chronicle', domain: 'stfrancischronicle.com', type: 'Local', geography: 'St Francis Bay' },
  { name: 'Jeffreys Bay News', domain: 'jeffreysbaynews.com', type: 'Local', geography: 'Jeffreys Bay' },
  { name: 'Karoo News', domain: 'karoonews.com', type: 'Local', geography: 'Graaff-Reinet' },
  { name: 'Graaff-Reinet Advertiser', domain: 'graaffreinetadvertiser.com', type: 'Local', geography: 'Graaff-Reinet' },
  { name: 'Knysna-Plett Herald', domain: 'knysnaplettherald.com', type: 'Local', geography: 'Garden Route/EC Border' },
  { name: 'George Herald', domain: 'georgeherald.com', type: 'Local', geography: 'Garden Route/EC Border' },
  { name: 'South Coast Herald', domain: 'southcoastherald.co.za', type: 'Local', geography: 'KZN/EC Border' },
  { name: 'The Gremlin', domain: 'thegremlin.co.za', type: 'Local', geography: 'Garden Route/EC Border' },
  { name: 'South Cape Forum', domain: 'southcapeforum.com', type: 'Local', geography: 'Garden Route/EC Border' },
  { name: 'Mossel Bay Advertiser', domain: 'mosselbayadvertiser.com', type: 'Local', geography: 'Garden Route/EC Border' },
  { name: 'Oudtshoorn Courant', domain: 'oudtshoorncourant.com', type: 'Local', geography: 'Garden Route/EC Border' },
  { name: 'Mid-Karoo Express', domain: 'midkarooexpress.co.za', type: 'Local', geography: 'Karoo' },
  { name: 'Eastern Cape Rising Sun', domain: 'risingsun.co.za', type: 'Local', geography: 'Eastern Cape' },
  { name: 'Public Eye', domain: 'publiceye.co.za', type: 'Local', geography: 'National/EC' },
  { name: 'The New Era', domain: 'thenewera.co.za', type: 'Local', geography: 'Eastern Cape' },
  { name: 'Community Gazette', domain: 'communitygazette.co.za', type: 'Local', geography: 'Eastern Cape' },
  { name: 'Amathole News', domain: 'amatholenews.co.za', type: 'Local', geography: 'Amathole District' },
  { name: 'Chris Hani News', domain: 'chrishaninews.co.za', type: 'Local', geography: 'Chris Hani District' },
  { name: 'Joe Gqabi News', domain: 'joegqabinews.co.za', type: 'Local', geography: 'Joe Gqabi District' },
  { name: 'OR Tambo News', domain: 'ortambonews.co.za', type: 'Local', geography: 'OR Tambo District' },
  { name: 'Alfred Nzo News', domain: 'alfrednzonews.co.za', type: 'Local', geography: 'Alfred Nzo District' },
  { name: 'Sarah Baartman News', domain: 'sarahbaartmannews.co.za', type: 'Local', geography: 'Sarah Baartman District' },
  { name: 'Nelson Mandela Bay News', domain: 'nelsonmandelabaynews.co.za', type: 'Local', geography: 'Nelson Mandela Bay' },
  { name: 'Buffalo City News', domain: 'buffalocitynews.co.za', type: 'Local', geography: 'Buffalo City' },
  { name: 'The Voice of the People', domain: 'voiceofthepeople.co.za', type: 'Local', geography: 'Eastern Cape' },
  { name: 'Local News Network (LNN)', domain: 'localnewsnetwork.co.za', type: 'Local', geography: 'National/EC' },
  { name: 'Caxton Local News', domain: 'caxton.co.za', type: 'Local', geography: 'National/EC' },
  { name: 'Media24 Local', domain: 'media24.com', type: 'Local', geography: 'National/EC' },
  { name: 'Arena Holdings Local', domain: 'arenaholdings.co.za', type: 'Local', geography: 'National/EC' },
  { name: 'The Daily Voice', domain: 'dailyvoice.co.za', type: 'Local', geography: 'National/EC' },
  { name: 'The Post', domain: 'thepost.co.za', type: 'Local', geography: 'National/EC' },
  { name: 'Sunday World', domain: 'sundayworld.co.za', type: 'National' },
  { name: 'City Press', domain: 'citypress.co.za', type: 'National' },
  { name: 'The New Age (Archives)', domain: 'thenewage.co.za', type: 'National' },
  { name: 'The Star', domain: 'thestar.co.za', type: 'National' },
  { name: 'Pretoria News', domain: 'pretorianews.co.za', type: 'National' },
  { name: 'Cape Times', domain: 'capetimes.co.za', type: 'National' },
  { name: 'Cape Argus', domain: 'capeargus.co.za', type: 'National' },
  { name: 'The Mercury', domain: 'themercury.co.za', type: 'National' },
  { name: 'Daily News', domain: 'dailynews.co.za', type: 'National' },
  { name: 'The Witness', domain: 'witness.co.za', type: 'National' },
  { name: 'Diamond Fields Advertiser', domain: 'dfa.co.za', type: 'National' },
  { name: 'Volksblad', domain: 'volksblad.com', type: 'National' },
  { name: 'Die Burger', domain: 'dieburger.com', type: 'National' },
  { name: 'Beeld', domain: 'beeld.com', type: 'National' },
  { name: 'Rapport', domain: 'rapport.co.za', type: 'National' },
  { name: 'Sunday Times', domain: 'sundaytimes.co.za', type: 'National' },
  { name: 'Financial Mail', domain: 'financialmail.co.za', type: 'National' },
  { name: 'The Media Online', domain: 'themediaonline.co.za', type: 'National' },
  { name: 'Bizcommunity', domain: 'bizcommunity.com', type: 'National' },
  { name: 'ITWeb South Africa', domain: 'itweb.co.za', type: 'National' },
  { name: 'TechCentral', domain: 'techcentral.co.za', type: 'National' },
  { name: 'MyBroadband', domain: 'mybroadband.co.za', type: 'National' },
  { name: 'Ventureburn', domain: 'ventureburn.com', type: 'National' },
  { name: 'Memeburn', domain: 'memeburn.com', type: 'National' },
  { name: 'Stuff South Africa', domain: 'stuff.co.za', type: 'National' },
  { name: 'Gearburn', domain: 'gearburn.com', type: 'National' },
  { name: 'Women24', domain: 'women24.com', type: 'National' },
  { name: 'Food24', domain: 'food24.com', type: 'National' },
  { name: 'Parent24', domain: 'parent24.com', type: 'National' },
  { name: 'Health24', domain: 'health24.com', type: 'National' },
  { name: 'Wheels24', domain: 'wheels24.com', type: 'National' },
  { name: 'Sport24', domain: 'sport24.co.za', type: 'National' },
  { name: 'SuperSport', domain: 'supersport.com', type: 'National' },
  { name: 'Kick Off', domain: 'kickoff.com', type: 'National' },
  { name: 'Soccer Laduma', domain: 'soccerladuma.co.za', type: 'National' },
  { name: 'Golf Digest South Africa', domain: 'golfdigest.co.za', type: 'National' },
  { name: 'SA Rugby Magazine', domain: 'sarugbymag.co.za', type: 'National' },
  { name: 'SA Cricket Mag', domain: 'sacricketmag.com', type: 'National' },
  { name: 'Runner\'s World South Africa', domain: 'runnersworld.co.za', type: 'National' },
  { name: 'Bicycling South Africa', domain: 'bicycling.co.za', type: 'National' },
  { name: 'Men\'s Health South Africa', domain: 'mh.co.za', type: 'National' },
  { name: 'Women\'s Health South Africa', domain: 'womenshealthsa.co.za', type: 'National' },
  { name: 'Cosmopolitan South Africa', domain: 'cosmopolitan.co.za', type: 'National' },
  { name: 'Glamour South Africa', domain: 'glamour.co.za', type: 'National' },
  { name: 'GQ South Africa', domain: 'gq.co.za', type: 'National' },
  { name: 'House & Garden South Africa', domain: 'houseandgarden.co.za', type: 'National' },
  { name: 'Architectural Digest South Africa', domain: 'ad-mag.co.za', type: 'National' },
  { name: 'Vogue South Africa', domain: 'vogue.co.za', type: 'National' },
  { name: 'Elle South Africa', domain: 'elle.co.za', type: 'National' },
  { name: 'Marie Claire South Africa', domain: 'marieclaire.co.za', type: 'National' },
  { name: 'Fairlady', domain: 'fairlady.com', type: 'National' },
  { name: 'Sarie', domain: 'sarie.com', type: 'National' },
  { name: 'Huisgenoot', domain: 'huisgenoot.com', type: 'National' },
  { name: 'YOU Magazine', domain: 'you.co.za', type: 'National' },
  { name: 'Drum Magazine', domain: 'drum.co.za', type: 'National' },
  { name: 'True Love Magazine', domain: 'truelove.co.za', type: 'National' },
  { name: 'Move! Magazine', domain: 'movemag.co.za', type: 'National' },
  { name: 'Bona Magazine', domain: 'bona.co.za', type: 'National' },
  { name: 'Destiny Magazine', domain: 'destinyconnect.com', type: 'National' },
  { name: 'Destiny Man', domain: 'destinyman.com', type: 'National' },
  { name: 'Finweek', domain: 'finweek.com', type: 'National' },
  { name: 'Entrepreneur South Africa', domain: 'entrepreneur.com/za', type: 'National' },
  { name: 'Forbes Africa', domain: 'forbesafrica.com', type: 'National' },
  { name: 'CNBC Africa', domain: 'cnbcafrica.com', type: 'National' },
  { name: 'Bloomberg South Africa', domain: 'bloomberg.com/africa', type: 'National' },
  { name: 'Reuters South Africa', domain: 'reuters.com/places/africa', type: 'National' },
  { name: 'AFP South Africa', domain: 'afp.com/en/news/africa', type: 'National' },
  { name: 'AP South Africa', domain: 'apnews.com/hub/africa', type: 'National' },
  { name: 'BBC News Africa', domain: 'bbc.com/news/world/africa', type: 'National' },
  { name: 'Al Jazeera Africa', domain: 'aljazeera.com/africa', type: 'National' },
  { name: 'CNN Africa', domain: 'edition.cnn.com/africa', type: 'National' },
  { name: 'Sky News Africa', domain: 'news.sky.com/africa', type: 'National' },
  { name: 'France 24 Africa', domain: 'france24.com/en/africa', type: 'National' },
  { name: 'Deutsche Welle Africa', domain: 'dw.com/en/africa/s-12756', type: 'National' },
  { name: 'Voice of America Africa', domain: 'voanews.com/africa', type: 'National' },
  { name: 'Radio France Internationale Africa', domain: 'rfi.fr/en/africa', type: 'National' },
  { name: 'African News Agency (ANA)', domain: 'africannewsagency.com', type: 'National' },
  { name: 'South African Press Association (SAPA) - Archives', domain: 'sapa.org.za', type: 'National' },

  // Official & Government (Expanded)
  { name: 'SA Government News Agency', domain: 'sanews.gov.za', type: 'Official' },
  { name: 'Eastern Cape Provincial Government', domain: 'ecprov.gov.za', type: 'Official', geography: 'Eastern Cape' },
  { name: 'Office of the Premier (EC)', domain: 'otp.ecprov.gov.za', type: 'Official', geography: 'Eastern Cape' },
  { name: 'GCIS', domain: 'gcis.gov.za', type: 'Official' },
  { name: 'Parliament of South Africa', domain: 'parliament.gov.za', type: 'Official' },
  { name: 'EC Provincial Treasury', domain: 'ectreasury.gov.za', type: 'Official', geography: 'Eastern Cape' },
  { name: 'EC Department of Health', domain: 'echealth.gov.za', type: 'Official', geography: 'Eastern Cape' },
  { name: 'EC Department of Education', domain: 'ecdoe.gov.za', type: 'Official', geography: 'Eastern Cape' },
  { name: 'EC Department of Transport', domain: 'ectransport.gov.za', type: 'Official', geography: 'Eastern Cape' },
  { name: 'EC Department of Human Settlements', domain: 'echumansettlements.gov.za', type: 'Official', geography: 'Eastern Cape' },
  { name: 'EC Department of Social Development', domain: 'ecdsd.gov.za', type: 'Official', geography: 'Eastern Cape' },
  { name: 'EC Department of Agriculture', domain: 'ecdrdar.gov.za', type: 'Official', geography: 'Eastern Cape' },
  { name: 'EC Department of Economic Development', domain: 'dedea.gov.za', type: 'Official', geography: 'Eastern Cape' },
  { name: 'EC Department of Cooperative Governance', domain: 'eccogta.gov.za', type: 'Official', geography: 'Eastern Cape' },
  { name: 'EC Department of Community Safety', domain: 'ecsafety.gov.za', type: 'Official', geography: 'Eastern Cape' },
  { name: 'EC Department of Public Works', domain: 'ecdpw.gov.za', type: 'Official', geography: 'Eastern Cape' },
  { name: 'Buffalo City Metro', domain: 'buffalocity.gov.za', type: 'Official', geography: 'Buffalo City' },
  { name: 'Nelson Mandela Bay Metro', domain: 'nelsonmandelabay.gov.za', type: 'Official', geography: 'Nelson Mandela Bay' },
  { name: 'Amathole District Municipality', domain: 'amathole.gov.za', type: 'Official', geography: 'Amathole' },
  { name: 'Chris Hani District Municipality', domain: 'chrishanidm.gov.za', type: 'Official', geography: 'Chris Hani' },
  { name: 'Joe Gqabi District Municipality', domain: 'jgdm.gov.za', type: 'Official', geography: 'Joe Gqabi' },
  { name: 'OR Tambo District Municipality', domain: 'ortambodm.gov.za', type: 'Official', geography: 'OR Tambo' },
  { name: 'Alfred Nzo District Municipality', domain: 'andm.gov.za', type: 'Official', geography: 'Alfred Nzo' },
  { name: 'Sarah Baartman District Municipality', domain: 'sarahbaartman.co.za', type: 'Official', geography: 'Sarah Baartman' },

  // Broadcasters (Expanded)
  { name: 'SABC News Online', domain: 'sabcnews.com', type: 'National' },
  { name: 'Newzroom Afrika', domain: 'newzroomafrika.tv', type: 'National' },
  { name: 'Jacaranda FM News', domain: 'jacarandafm.com', type: 'National' },
  { name: 'Algoa FM News', domain: 'algoafm.co.za', type: 'Regional', geography: 'Eastern Cape' },
  { name: 'TruFM News', domain: 'trufm.co.za', type: 'Regional', geography: 'Eastern Cape' },
  { name: 'Umhlobo Wenene FM News', domain: 'umhlobowenenefm.co.za', type: 'Regional', geography: 'Eastern Cape' },
  { name: 'Radio 702', domain: '702.co.za', type: 'National' },
  { name: 'CapeTalk', domain: 'capetalk.co.za', type: 'National' },
  { name: 'Kfm 94.5', domain: 'kfm.co.za', type: 'National' },
  { name: 'East Coast Radio', domain: 'ecr.co.za', type: 'National' },
  { name: 'Heart FM', domain: 'heartfm.co.za', type: 'National' },
  { name: 'Good Hope FM', domain: 'goodhopefm.co.za', type: 'National' },
  { name: 'Metro FM', domain: 'metrofm.co.za', type: 'National' },
  { name: '5FM', domain: '5fm.co.za', type: 'National' },
  { name: 'Radio 2000', domain: 'radio2000.co.za', type: 'National' },
  { name: 'RSG', domain: 'rsg.co.za', type: 'National' },
  { name: 'SAfm', domain: 'safm.co.za', type: 'National' },
  { name: 'Lotus FM', domain: 'lotusfm.co.za', type: 'National' },
  { name: 'Ukhozi FM', domain: 'ukhozifm.co.za', type: 'National' },
  { name: 'Lesedi FM', domain: 'lesedifm.co.za', type: 'National' },
  { name: 'Motsweding FM', domain: 'motswedingfm.co.za', type: 'National' },
  { name: 'Thobela FM', domain: 'thobelafm.co.za', type: 'National' },
  { name: 'Phalaphala FM', domain: 'phalaphalafm.co.za', type: 'National' },
  { name: 'Munghana Lonene FM', domain: 'munghanalonenefm.co.za', type: 'National' },
  { name: 'Ligwalagwala FM', domain: 'ligwalagwalafm.co.za', type: 'National' },
  { name: 'Ikwekwezi FM', domain: 'ikwekwezifm.co.za', type: 'National' },
  { name: 'X-K FM', domain: 'xkfm.co.za', type: 'National' },

  // Niche & Business (Expanded)
  { name: 'Engineering News', domain: 'engineeringnews.co.za', type: 'National' },
  { name: 'ITWeb', domain: 'itweb.co.za', type: 'National' },
  { name: 'Farmer\'s Weekly', domain: 'farmersweekly.co.za', type: 'National' },
  { name: 'Landbouweekblad', domain: 'landbou.com', type: 'National' },
  { name: 'Mining Weekly', domain: 'miningweekly.com', type: 'National' },
  { name: 'Creamer Media', domain: 'creamermedia.co.za', type: 'National' },
  { name: 'Infrastructure News', domain: 'infrastructurenews.co.za', type: 'National' },
  { name: 'Water Briefing Africa', domain: 'waterbriefingafrica.com', type: 'National' },
  { name: 'Energy News Africa', domain: 'energynewsafrica.com', type: 'National' },
  { name: 'Green Economy Journal', domain: 'greeneconomyjournal.com', type: 'National' },
  { name: 'Sustainability Africa', domain: 'sustainabilityafrica.com', type: 'National' },
  { name: 'Responsible Business', domain: 'responsiblebusiness.co.za', type: 'National' },
  { name: 'CSI South Africa', domain: 'csi-southafrica.co.za', type: 'National' },
  { name: 'NGO Pulse', domain: 'ngopulse.org', type: 'National' },
  { name: 'Social TV', domain: 'social-tv.co.za', type: 'National' },
  { name: 'The Conversation Africa', domain: 'theconversation.com/africa', type: 'National' },
  { name: 'Daily Maverick 168', domain: 'dailymaverick.co.za/dm168', type: 'National' },
  { name: 'Financial Post', domain: 'financialpost.co.za', type: 'National' },
  { name: 'Business Report', domain: 'businessreport.co.za', type: 'National' },
  { name: 'Personal Finance', domain: 'personalfinance.co.za', type: 'National' },
  { name: 'IOL Property', domain: 'property.iol.co.za', type: 'National' },
  { name: 'IOL Motoring', domain: 'motoring.iol.co.za', type: 'National' },
  { name: 'IOL Travel', domain: 'travel.iol.co.za', type: 'National' },
  { name: 'IOL Entertainment', domain: 'entertainment.iol.co.za', type: 'National' },
  { name: 'IOL Lifestyle', domain: 'lifestyle.iol.co.za', type: 'National' },
  { name: 'IOL Sport', domain: 'sport.iol.co.za', type: 'National' },
  { name: 'IOL Technology', domain: 'technology.iol.co.za', type: 'National' },
  { name: 'IOL Education', domain: 'education.iol.co.za', type: 'National' },
  { name: 'IOL Health', domain: 'health.iol.co.za', type: 'National' },
  { name: 'IOL Business', domain: 'business.iol.co.za', type: 'National' },
  { name: 'IOL News', domain: 'news.iol.co.za', type: 'National' },
  { name: 'IOL World', domain: 'world.iol.co.za', type: 'National' },
  { name: 'IOL Opinion', domain: 'opinion.iol.co.za', type: 'National' },
  { name: 'IOL Politics', domain: 'politics.iol.co.za', type: 'National' },
  { name: 'IOL Sci-Tech', domain: 'scitech.iol.co.za', type: 'National' },
  { name: 'IOL Jobs', domain: 'jobs.iol.co.za', type: 'National' },
  { name: 'IOL Classifieds', domain: 'classifieds.iol.co.za', type: 'National' },
  { name: 'IOL Dating', domain: 'dating.iol.co.za', type: 'National' },
  { name: 'IOL Auctions', domain: 'auctions.iol.co.za', type: 'National' },
  { name: 'IOL Property Search', domain: 'propertysearch.iol.co.za', type: 'National' },
  { name: 'IOL Car Search', domain: 'carsearch.iol.co.za', type: 'National' },
  { name: 'IOL Job Search', domain: 'jobsearch.iol.co.za', type: 'National' },
  { name: 'IOL Business Directory', domain: 'businessdirectory.iol.co.za', type: 'National' },
];

